### ISSUE TITLE
Okteto up - VSCode can't open SSH session DNS issues

### ISSUE THREAD

**Issue by interpeix** [okteto/remote-kubernetes#176]
**Describe the bug**
After using the Okteto Up command through VSCode with Remote - Kubernetes extension I'm not able to establish SSH connection to the remote dev pod. 

Here is the log:

[22:44:01.341] Log Level: 2
[22:44:01.341] remote-ssh@0.76.1
[22:44:01.341] darwin arm64
[22:44:01.349] SSH Resolver called for "ssh-remote+hello-world.okteto", attempt 1
[22:44:01.350] "remote.SSH.useLocalServer": true
[22:44:01.350] "remote.SSH.path": undefined
[22:44:01.350] "remote.SSH.configFile": /var/folders/8p/54xm_ynj44b_b4_f3cm5d_fh0000gn/T/gitpod_ssh_config-30476-aq7axS9QKiop
[22:44:01.350] "remote.SSH.useFlock": true
[22:44:01.351] "remote.SSH.lockfilesInTmp": false
[22:44:01.351] "remote.SSH.localServerDownload": auto
[22:44:01.351] "remote.SSH.remoteServerListenOnSocket": false
[22:44:01.351] "remote.SSH.showLoginTerminal": false
[22:44:01.352] "remote.SSH.defaultExtensions": ["gitpod.gitpod-remote-ssh"]
[22:44:01.352] "remote.SSH.loglevel": 2
[22:44:01.352] "remote.SSH.enableDynamicForwarding": true
[22:44:01.352] "remote.SSH.enableRemoteCommand": false
[22:44:01.352] "remote.SSH.serverPickPortsFromRange": {}
[22:44:01.353] "remote.SSH.serverInstallPath": {}
[22:44:01.355] SSH Resolver called for host: hello-world.okteto
[22:44:01.355] Setting up SSH remote "hello-world.okteto"
[22:44:01.357] Acquiring local install lock: /var/folders/8p/54xm_ynj44b_b4_f3cm5d_fh0000gn/T/vscode-remote-ssh-0619bc04-install.lock
[22:44:01.361] Looking for existing server data file at /Users/r.ferrer/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-0619bc04-c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1-0.76.1/data.json
[22:44:01.362] Using commit id "c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1" and quality "stable" for server
[22:44:01.364] Install and start server if needed
[22:44:01.367] PATH: /opt/homebrew/bin:/opt/homebrew/sbin:/opt/homebrew/opt/mysql-client/bin:/opt/homebrew/opt/libpq/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/homebrew/bin/
[22:44:01.367] Checking ssh with "ssh -V"
[22:44:01.376] > OpenSSH_8.6p1, LibreSSL 2.8.3

[22:44:01.377] Using SSH config file "/var/folders/8p/54xm_ynj44b_b4_f3cm5d_fh0000gn/T/gitpod_ssh_config-30476-aq7axS9QKiop"
[22:44:01.378] askpass server listening on /var/folders/8p/54xm_ynj44b_b4_f3cm5d_fh0000gn/T/vscode-ssh-askpass-3579ebdfe701590cfb864b0063122ea4ce1848f5.sock
[22:44:01.378] Spawning local server with {"serverId":1,"ipcHandlePath":"/var/folders/8p/54xm_ynj44b_b4_f3cm5d_fh0000gn/T/vscode-ssh-askpass-60ba9181d846f4ad8366a349cc0ab0ff12ba36e9.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","60570","-o","ConnectTimeout=15","-F","/var/folders/8p/54xm_ynj44b_b4_f3cm5d_fh0000gn/T/gitpod_ssh_config-30476-aq7axS9QKiop","hello-world.okteto"],"serverDataFolderName":".vscode-server","dataFilePath":"/Users/r.ferrer/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-0619bc04-c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1-0.76.1/data.json"}
[22:44:01.378] Local server env: {"SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.H8tcTsh62i/Listeners","SHELL":"/opt/homebrew/bin/fish","DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/r.ferrer/.vscode/extensions/ms-vscode-remote.remote-ssh-0.76.1/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/MacOS/Electron","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/Users/r.ferrer/.vscode/extensions/ms-vscode-remote.remote-ssh-0.76.1/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/8p/54xm_ynj44b_b4_f3cm5d_fh0000gn/T/vscode-ssh-askpass-3579ebdfe701590cfb864b0063122ea4ce1848f5.sock"}
[22:44:01.379] Spawned 41870
[22:44:01.436] > local-server-1> Spawned ssh, pid=41876
[22:44:01.440] stderr> OpenSSH_8.6p1, LibreSSL 2.8.3
[22:44:01.442] stderr> ssh: Could not resolve hostname hello-world.okteto: nodename nor servname provided, or not known
[22:44:01.443] > local-server-1> ssh child died, shutting down
[22:44:01.444] Local server exit: 0
[22:44:01.444] Received install output: local-server-1> Spawned ssh, pid=41876
OpenSSH_8.6p1, LibreSSL 2.8.3
ssh: Could not resolve hostname hello-world.okteto: nodename nor servname provided, or not known
local-server-1> ssh child died, shutting down

[22:44:01.445] Resolver error: Error: Could not resolve hostname
	at Function.Offline (/Users/r.ferrer/.vscode/extensions/ms-vscode-remote.remote-ssh-0.76.1/out/extension.js:1:586092)
	at /Users/r.ferrer/.vscode/extensions/ms-vscode-remote.remote-ssh-0.76.1/out/extension.js:1:583388
	at Object.t.handleInstallOutput (/Users/r.ferrer/.vscode/extensions/ms-vscode-remote.remote-ssh-0.76.1/out/extension.js:1:583875)
	at Object.e [as tryInstallWithLocalServer] (/Users/r.ferrer/.vscode/extensions/ms-vscode-remote.remote-ssh-0.76.1/out/extension.js:1:625033)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async /Users/r.ferrer/.vscode/extensions/ms-vscode-remote.remote-ssh-0.76.1/out/extension.js:1:644084
	at async Object.t.withShowDetailsEvent (/Users/r.ferrer/.vscode/extensions/ms-vscode-remote.remote-ssh-0.76.1/out/extension.js:1:647831)
	at async /Users/r.ferrer/.vscode/extensions/ms-vscode-remote.remote-ssh-0.76.1/out/extension.js:1:623505
	at async b (/Users/r.ferrer/.vscode/extensions/ms-vscode-remote.remote-ssh-0.76.1/out/extension.js:1:620011)
	at async Object.t.resolveWithLocalServer (/Users/r.ferrer/.vscode/extensions/ms-vscode-remote.remote-ssh-0.76.1/out/extension.js:1:623120)
	at async Object.t.resolve (/Users/r.ferrer/.vscode/extensions/ms-vscode-remote.remote-ssh-0.76.1/out/extension.js:1:645441)
	at async /Users/r.ferrer/.vscode/extensions/ms-vscode-remote.remote-ssh-0.76.1/out/extension.js:1:722872
[22:44:01.447] ------

**Expected behavior**
Establish the SSH Connection to the pod and start working on it.

**Desktop (please complete the following information):**
 - OS: MacOs X Monterey 12.2.1 on M1

**Comment by interpeix** [comment]
Finally I figure out what the problem is. The Gitpod VSCode extension have changed the default SSH config file. Once uninstalled and restored the default config file, the Okteto extension will be able to connect without issues.
